from enum import StrEnum


class CompatibilityStatus(StrEnum):
    VERIFIED_COMPATIBLE = "VERIFIED_COMPATIBLE"
    UNKNOWN = "UNKNOWN"
    INCOMPATIBLE = "INCOMPATIBLE"
    EXPIRED = "EXPIRED"


class AssertionState(StrEnum):
    VERIFIED = "VERIFIED"
    UNKNOWN = "UNKNOWN"
    INCOMPATIBLE = "INCOMPATIBLE"


class HandoffAction(StrEnum):
    REFERRAL = "REFERRAL"


class IncidentState(StrEnum):
    REPORTED = "REPORTED"
    AUTHORIZED = "AUTHORIZED"
    PROVIDER_CHECKING = "PROVIDER_CHECKING"
    OPTIONS_READY = "OPTIONS_READY"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HANDOFF = "HANDOFF"
    NO_COMPATIBLE_OPTION = "NO_COMPATIBLE_OPTION"
    DEADLINE_EXPIRED = "DEADLINE_EXPIRED"
    CALL_BUDGET_EXHAUSTED = "CALL_BUDGET_EXHAUSTED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
